a = input('Digite algo:')
print('O tipo primitivo desse valor é', type(a))
print('So tem espaços? {}'.format(a.isspace()))
print('É um número?,{}'.format(a.isnumeric()))
print('É alfabetico?{}'.format(a.isalpha()))
print('É alfanumerico?{}'.format(a.isalnum()))
print('Está em maiusculo?{}'.format(a.isupper()))
print('Está em minusculo?{}'.format(a.islower()))
print('Está capitalzada?{}'.format(a.istitle()))
